### ISSUE TITLE
erl_call timeout when using long name

### ISSUE THREAD

**Issue by evnu** [ppikula/vim-wrangler#2]
On my machine (ArchLinux, Erlang/OTP 19 [erts-8.1.1]), `StartWranglerServer()` fails because of `erl_call`. This is the result when I call `erl_call` directly from the command line:

```
/usr/lib/erlang/lib/erl_interface-3.9.1/bin/erl_call -s -name wrangler_vim -x 'erl -pa /usr/lib/erlang/lib/wrangler-1.2.0/ebin' 
erl_call: unable to start node, error = -5
```

It turns out that my system does not use a FQDN and hence short names are required for Erlang. Would it be possible to use `-sname` instead of `-name` in `StartWranglerServer()`?

For the record, I can also work around this issue by setting a FQDN manually with `sudo hostname -f <machine>.<domain>`.

**Comment by ppikula** [comment]
Hi! I don't recall any reason why there is `name` instead of `sname`, so probably we can use `sname`. Would like to create a pull request with the change?
